channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python>=3.7.5,<4
  - pip
  - seaborn
  - scikit-learn
  - pytorch::pytorch=2=*cuda*
  - pytorch::pytorch-cuda>=11.8,<12
  - pytorch::torchvision
  - pytorch::torchaudio
  - defaults::sentencepiece
  - defaults::scikit-learn
  - senyan.dev::cudatoolkit-dev
  - conda-forge::transformers>=4.30,<5
  - conda-forge::tokenizers
  - conda-forge::datasets>=2.13,<3
  - conda-forge::accelerate=0.20.3
  - conda-forge::python-duckdb
  - conda-forge::gsutil
  - pip:
    - -e ../promptsource/
    - mdmm
    - optax<0.1.8
    - protobuf<4
    - auto-gptq[triton]
    - ai2-tango[all]==1.3.2
